#! /usr/bin/python

TYPE_FACE = 1
TYPE_NONFACE = -1

TRAIN_FACE_FILE_PREFIX = 'face'
TRAIN_NON_FACE_FILE_PREFIX_1 = 'B1_'
TRAIN_NON_FACE_FILE_PREFIX_2 = 'B5_'
TRAIN_NON_FACE_FILE_PREFIX_3 = 'B20_'
TEST_IMAGE_PREFIX = 'cmu_'